main_timer_rate: 30 # [Hz]

coincidence_matching:
  method: 0 # { 0 = time, 1 = id }

detector:

  sensor_thickness: 0.002 # [m]
  time_constant: 86.0 # [ns]

  pixel_pitch: 0.000055 # [m]

prior:

  enabled: true
  # energy: 59.0 # [kev]
  energy: 662.0 # [kev]

plotting:

  cone_height: 10.0 # [m]
  clear_cones: true
